version: "3.6"
services:
  mysqldb:
    image: mysql
    networks:
      - desafio-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=desafiodb
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  desafioApp:
    image: brunovaranha2/desafio-tecnico
    ports:
      - "8080:8080"
    networks:
      - desafio-network
    depends_on:
      mysqldb:
        condition: service_healthy




networks:
  desafio-network: